version: '3'

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '10001:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
      UPLOAD_LIMIT: 512M
    networks:
      - wpsite
  # Wordpress
  wordpress:
    build: .
    depends_on:
      - db
    image: custom-wordpress:php7.4-apache-xdebug
    ports:
      - '10000:80'
    restart: always
    volumes:
      - './:/var/www/html'
      - './xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini'
      - './custom.ini:/usr/local/etc/php/conf.d/custom.ini'
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: